// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreSystem.Infrastructure.Persistence;

#nullable disable

namespace StoreSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128202031_SeedDefaultPermissions")]
    partial class SeedDefaultPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("IX_Category_InventoryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Category_Name");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Customer_Email");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Customer_Name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Customer_Phone");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_Inventory_StoreId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Product.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 990, DateTimeKind.Utc).AddTicks(3200),
                            Name = "Product Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Product.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 990, DateTimeKind.Utc).AddTicks(5734),
                            Name = "Product Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Product.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 990, DateTimeKind.Utc).AddTicks(6160),
                            Name = "Product Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Product.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 990, DateTimeKind.Utc).AddTicks(6168),
                            Name = "Product Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Category.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 990, DateTimeKind.Utc).AddTicks(9937),
                            Name = "Category Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Category.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 990, DateTimeKind.Utc).AddTicks(9998),
                            Name = "Category Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Category.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(7),
                            Name = "Category Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Category.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(13),
                            Name = "Category Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Sales.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(19),
                            Name = "Sales Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Sales.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(28),
                            Name = "Sales Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 11,
                            Code = "Sales.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(34),
                            Name = "Sales Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 12,
                            Code = "Sales.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(41),
                            Name = "Sales Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 13,
                            Code = "Purchase.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(47),
                            Name = "Purchase Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 14,
                            Code = "Purchase.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(53),
                            Name = "Purchase Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 15,
                            Code = "Purchase.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(59),
                            Name = "Purchase Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 16,
                            Code = "Purchase.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(65),
                            Name = "Purchase Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 17,
                            Code = "Stock.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(100),
                            Name = "Stock Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 18,
                            Code = "Stock.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(110),
                            Name = "Stock Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Stock.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(117),
                            Name = "Stock Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 20,
                            Code = "Stock.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(123),
                            Name = "Stock Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 21,
                            Code = "Customer.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(130),
                            Name = "Customer Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 22,
                            Code = "Customer.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(136),
                            Name = "Customer Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Customer.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(142),
                            Name = "Customer Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 24,
                            Code = "Customer.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(148),
                            Name = "Customer Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 25,
                            Code = "Supplier.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(153),
                            Name = "Supplier Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 26,
                            Code = "Supplier.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(159),
                            Name = "Supplier Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 27,
                            Code = "Supplier.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(165),
                            Name = "Supplier Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 28,
                            Code = "Supplier.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(171),
                            Name = "Supplier Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 29,
                            Code = "Dashboard.View",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(183),
                            Name = "Dashboard View",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 30,
                            Code = "Reports.View",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(190),
                            Name = "Reports View",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 31,
                            Code = "Store.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(196),
                            Name = "Store Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 32,
                            Code = "Store.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(201),
                            Name = "Store Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 33,
                            Code = "Store.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(208),
                            Name = "Store Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 34,
                            Code = "Store.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(218),
                            Name = "Store Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 35,
                            Code = "Employee.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(225),
                            Name = "Employee Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 36,
                            Code = "Employee.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(393),
                            Name = "Employee Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 37,
                            Code = "Employee.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(405),
                            Name = "Employee Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 38,
                            Code = "Employee.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(412),
                            Name = "Employee Delete",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 39,
                            Code = "Payment.Create",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(419),
                            Name = "Payment Create",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 40,
                            Code = "Payment.Read",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(426),
                            Name = "Payment Read",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 41,
                            Code = "Payment.Update",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(431),
                            Name = "Payment Update",
                            UpdateByUserId = "system"
                        },
                        new
                        {
                            Id = 42,
                            Code = "Payment.Delete",
                            CreateByUserId = "system",
                            CreatedAt = new DateTime(2025, 11, 28, 20, 20, 27, 991, DateTimeKind.Utc).AddTicks(436),
                            Name = "Payment Delete",
                            UpdateByUserId = "system"
                        });
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.ProcessedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("ProcessedEvents");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Product_CategoryId");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Product_Name");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("StoreId")
                        .HasDatabaseName("IX_Product_StoreId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PurchaseInvoice_CreatedAt");

                    b.HasIndex("StoreId");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("IX_PurchaseInvoice_SupplierId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PurchaseItem_ProductId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DueAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_SalesInvoice_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_SalesInvoice_CustomerId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SalesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_SalesItem_ProductId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("SalesItems");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UpdateByUserId");

                    b.HasIndex("InventoryId", "ProductId")
                        .HasDatabaseName("IX_Stock_Inventory_Product");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_StockMovement_Date");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("IX_StockMovement_InventoryId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_StockMovement_ProductId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Store_Name");

                    b.HasIndex("UpdateByUserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Store_UserId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.StoreEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UpdateByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Supplier_Email");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Supplier_Name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Supplier_Phone");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SupplierProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierSku")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreateByUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UpdateByUserId");

                    b.ToTable("SupplierProducts");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.TokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Category", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Inventory", "Inventory")
                        .WithMany("categories")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Inventory");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Customer", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Inventory", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Store");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Payment", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.SalesInvoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Payment_SalesInvoice");

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Permission", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.ProcessedEvent", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Product", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreateByUser");

                    b.Navigation("Store");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", "Store")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Store");

                    b.Navigation("Supplier");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.PurchaseItem", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Product", "Product")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Role", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", "Store")
                        .WithMany("Roles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Store");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Role", "Roles")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Permission");

                    b.Navigation("Roles");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SalesInvoice", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", "Store")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Customer");

                    b.Navigation("Store");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SalesItem", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Product", "Product")
                        .WithMany("SalesItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.SalesInvoice", "SalesInvoice")
                        .WithMany("SalesItems")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Stock", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Inventory", "Inventory")
                        .WithMany("Stocks")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Inventory");

                    b.Navigation("Product");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.StockMovement", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", null)
                        .WithMany("stockMovements")
                        .HasForeignKey("StoreId");

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Inventory");

                    b.Navigation("Product");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Store", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("UpdateByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.StoreEmployee", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Roles");

                    b.Navigation("Store");

                    b.Navigation("UpdateByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Supplier", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SupplierProduct", b =>
                {
                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "CreateByUser")
                        .WithMany()
                        .HasForeignKey("CreateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Product", "Product")
                        .WithMany("SupplierProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreSystem.Core.Entities.ApplicationUser", "UpdateByUser")
                        .WithMany()
                        .HasForeignKey("UpdateByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateByUser");

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("UpdateByUser");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Customer", b =>
                {
                    b.Navigation("SalesInvoices");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Inventory", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("categories");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Product", b =>
                {
                    b.Navigation("PurchaseItems");

                    b.Navigation("SalesItems");

                    b.Navigation("StockMovements");

                    b.Navigation("Stocks");

                    b.Navigation("SupplierProducts");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.SalesInvoice", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SalesItems");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Products");

                    b.Navigation("PurchaseInvoices");

                    b.Navigation("Roles");

                    b.Navigation("SalesInvoices");

                    b.Navigation("stockMovements");
                });

            modelBuilder.Entity("StoreSystem.Core.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
